chore: documentation for record
ProvableHQ/snarkVM pull request #16
Opened 2024-06-11 06:53 UTC by alexanderblv

## Motivation
Closes https://github.com/AleoNet/snarkVM/issues/2132
(Write your motivation here)

## Test Plan

(Write your test plan here)

## Related PRs

(Link your related PRs here)

2024-06-11 11:21 UTC, vicsn commented
Thx for the chore! Do you mind keeping the original comment (adding your new line above it)? And doing the same for the function below it? I assume the original line was useful for the original author and may be for future readers.

2024-06-12 10:21 UTC, alexanderblv commented
> Thx for the chore! Do you mind keeping the original comment (adding your new line above it)? And doing the same for the function below it? I assume the original line was useful for the original author and may be for future readers.

Done!

2024-06-12 18:00 UTC, vicsn approved these changes

2024-06-12 18:05 UTC, alexanderblv commented
@vicsn It seems I don't have the rights to put this PR to merge queue. Could you do that?

2024-06-12 18:07 UTC, vicsn commented
I don't either, it's not high priority so can be a while

2024-07-02 21:12 UTC, raychu86 requested changes

2024-07-02 21:12 UTC, raychu86 commented on console/program/src/data/record/is_owner.rs
> +    /// Determines whether the record belongs to the account.
```suggestion
    /// Returns `true` if the given view key is the owner of the record. 
```

2024-07-02 21:22 UTC, raychu86 commented
Closing in favor of https://github.com/AleoNet/snarkVM/pull/2513

2024-07-02 21:22 UTC, closed without merging